make a full keyboard map for french and belgium azerty keyboards
brummer10/Mamba pull request #11
Opened 2020-08-30 11:45 UTC by Houston4444

Here is the full map for french and belgium (wallon) keyboards.

you can find an image of a french keyboard to see exactly what I mean here: [here](http://images2.minutemediacdn.com/image/upload/c_fit,f_auto,fl_lossy,q_auto,w_728/v1555925942/shape/mentalfloss/azerty.png)

It uses all the usable keys of the keyboard.
The High F note at the bottom right is used by "ù" because shift (Maj) is a large key and F# can be "*".
We see the same scheme at the top right, F can't be dead circumflex (it doesn't works), so it becomes ")", but the following F# is "=" and G is "$", so at the good place.

Also, the "<" at the bottom left is used for B-1, because there is no good reason to not use this key if it exists (this key doesn't exists on some keyboards).

Maybe on the GUI azerty, qwertz and qwerty could be sub-menus, I didn't do that, but I think that if many keymaps are written, it can be directly more clear for users.

2020-08-30 16:21 UTC, brummer10 commented on src/xkeyboard.c
> +        case(XK_a) : (*midi_key) = 24.0; /* a = C1 */
the keymaps should be sorted by the returning midi_key. Otherwise it becomes hard to maintain in the long run.

2020-08-30 16:25 UTC, brummer10 commented on src/xkeyboard.c
> +        case(XK_parenleft) : (*midi_key) = 30.0; /* ( */
As my previous comment, when sorted, you could rewrite this as 
 ```
 case(XK_asterisk) :
 case(XK_parenleft) : (*midi_key) = 30.0;
```

2020-08-30 16:26 UTC, brummer10 commented on src/xkeyboard.c
> +void keysym_azerty_afnor_to_midi_key(long inkey, float *midi_key) {
what is this? This isn't used anywhere.

2020-08-30 16:30 UTC, brummer10 requested changes
Hi @Houston4444 
Thanks for your pull request.
Unfortunately I cant accept it as it contains a lot out-commented code, which should either be used  or be removed. Also the keymaps should be sorted after the returning midi_key for easier maintenance.

Other than that, it would be nice to have support for azerty_fr and azzerty_bg here in Mamba.

regards
hermann

2020-08-30 16:53 UTC, Houston4444 commented on src/xkeyboard.c
> +        case(XK_a) : (*midi_key) = 24.0; /* a = C1 */
Humm, Are you sure ?
Here it is sorted by note considering two ranges, the top one and the bottom one.
The bottom one from B-1 (">") to F#1 ("*"), the top one from C1 ("a") to G2 ("$").
Because there are some notes in the two ranges (C1 to F#1), I think it's more readable to see the two ranges separately, but I can do it, no problem.

2020-08-30 16:57 UTC, Houston4444 commented on src/xkeyboard.c
> +void keysym_azerty_afnor_to_midi_key(long inkey, float *midi_key) {
Yes, true.
It's another standard decided by a french speaking institution. I never seen this keyboard anywhere, but it could exists in the future. AFNOR is an organism specifying many standards for many kind of things.

2020-08-30 17:05 UTC, brummer10 commented on src/xkeyboard.c
> +void keysym_azerty_afnor_to_midi_key(long inkey, float *midi_key) {
So I guess I'll move the keymap definitions in it's own file when you've reworked the pull request, as it becomes real large.

2020-08-31 03:35 UTC, merged

2020-08-31 03:36 UTC, brummer10 commented
Thanks, looks good now, merged.